//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhAgenteServicios.ServicioHydroSesion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_USUARIO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_ENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRE_COMPLETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERFILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PERFIL_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((this.ESTADOField.Equals(value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_ENTIDAD {
            get {
                return this.ID_ENTIDADField;
            }
            set {
                if ((this.ID_ENTIDADField.Equals(value) != true)) {
                    this.ID_ENTIDADField = value;
                    this.RaisePropertyChanged("ID_ENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_USUARIO {
            get {
                return this.ID_USUARIOField;
            }
            set {
                if ((this.ID_USUARIOField.Equals(value) != true)) {
                    this.ID_USUARIOField = value;
                    this.RaisePropertyChanged("ID_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE_COMPLETO {
            get {
                return this.NOMBRE_COMPLETOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRE_COMPLETOField, value) != true)) {
                    this.NOMBRE_COMPLETOField = value;
                    this.RaisePropertyChanged("NOMBRE_COMPLETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERFIL {
            get {
                return this.PERFILField;
            }
            set {
                if ((object.ReferenceEquals(this.PERFILField, value) != true)) {
                    this.PERFILField = value;
                    this.RaisePropertyChanged("PERFIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PERFIL_ID {
            get {
                return this.PERFIL_IDField;
            }
            set {
                if ((this.PERFIL_IDField.Equals(value) != true)) {
                    this.PERFIL_IDField = value;
                    this.RaisePropertyChanged("PERFIL_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_RESULTADO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_RESULTADO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_RESULTADOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_RESULTADO {
            get {
                return this.ID_RESULTADOField;
            }
            set {
                if ((this.ID_RESULTADOField.Equals(value) != true)) {
                    this.ID_RESULTADOField = value;
                    this.RaisePropertyChanged("ID_RESULTADO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_DETALLE_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_DETALLE_USUARIO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AUD_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLAVEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPLEMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ENTIDAD_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXPEDICIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXPEDICION_ABREVIACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EXPEDICION_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FECHA_NACIMIENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GENEROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GENERO_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_IDENTIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PERSONA_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRIMER_APELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEGUNDO_APELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_IDENTIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TIPO_IDENTIFICACION_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AUD_ESTADO {
            get {
                return this.AUD_ESTADOField;
            }
            set {
                if ((this.AUD_ESTADOField.Equals(value) != true)) {
                    this.AUD_ESTADOField = value;
                    this.RaisePropertyChanged("AUD_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLAVE {
            get {
                return this.CLAVEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLAVEField, value) != true)) {
                    this.CLAVEField = value;
                    this.RaisePropertyChanged("CLAVE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPLEMENTO {
            get {
                return this.COMPLEMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPLEMENTOField, value) != true)) {
                    this.COMPLEMENTOField = value;
                    this.RaisePropertyChanged("COMPLEMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ENTIDAD_ID {
            get {
                return this.ENTIDAD_IDField;
            }
            set {
                if ((this.ENTIDAD_IDField.Equals(value) != true)) {
                    this.ENTIDAD_IDField = value;
                    this.RaisePropertyChanged("ENTIDAD_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((this.ESTADOField.Equals(value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXPEDICION {
            get {
                return this.EXPEDICIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EXPEDICIONField, value) != true)) {
                    this.EXPEDICIONField = value;
                    this.RaisePropertyChanged("EXPEDICION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXPEDICION_ABREVIACION {
            get {
                return this.EXPEDICION_ABREVIACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EXPEDICION_ABREVIACIONField, value) != true)) {
                    this.EXPEDICION_ABREVIACIONField = value;
                    this.RaisePropertyChanged("EXPEDICION_ABREVIACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EXPEDICION_ID {
            get {
                return this.EXPEDICION_IDField;
            }
            set {
                if ((this.EXPEDICION_IDField.Equals(value) != true)) {
                    this.EXPEDICION_IDField = value;
                    this.RaisePropertyChanged("EXPEDICION_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FECHA_NACIMIENTO {
            get {
                return this.FECHA_NACIMIENTOField;
            }
            set {
                if ((this.FECHA_NACIMIENTOField.Equals(value) != true)) {
                    this.FECHA_NACIMIENTOField = value;
                    this.RaisePropertyChanged("FECHA_NACIMIENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GENERO {
            get {
                return this.GENEROField;
            }
            set {
                if ((object.ReferenceEquals(this.GENEROField, value) != true)) {
                    this.GENEROField = value;
                    this.RaisePropertyChanged("GENERO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GENERO_ID {
            get {
                return this.GENERO_IDField;
            }
            set {
                if ((this.GENERO_IDField.Equals(value) != true)) {
                    this.GENERO_IDField = value;
                    this.RaisePropertyChanged("GENERO_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_USUARIO {
            get {
                return this.ID_USUARIOField;
            }
            set {
                if ((this.ID_USUARIOField.Equals(value) != true)) {
                    this.ID_USUARIOField = value;
                    this.RaisePropertyChanged("ID_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGIN {
            get {
                return this.LOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.LOGINField, value) != true)) {
                    this.LOGINField = value;
                    this.RaisePropertyChanged("LOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_IDENTIFICACION {
            get {
                return this.NUMERO_IDENTIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_IDENTIFICACIONField, value) != true)) {
                    this.NUMERO_IDENTIFICACIONField = value;
                    this.RaisePropertyChanged("NUMERO_IDENTIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PERSONA_ID {
            get {
                return this.PERSONA_IDField;
            }
            set {
                if ((this.PERSONA_IDField.Equals(value) != true)) {
                    this.PERSONA_IDField = value;
                    this.RaisePropertyChanged("PERSONA_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRIMER_APELLIDO {
            get {
                return this.PRIMER_APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRIMER_APELLIDOField, value) != true)) {
                    this.PRIMER_APELLIDOField = value;
                    this.RaisePropertyChanged("PRIMER_APELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEGUNDO_APELLIDO {
            get {
                return this.SEGUNDO_APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.SEGUNDO_APELLIDOField, value) != true)) {
                    this.SEGUNDO_APELLIDOField = value;
                    this.RaisePropertyChanged("SEGUNDO_APELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_IDENTIFICACION {
            get {
                return this.TIPO_IDENTIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_IDENTIFICACIONField, value) != true)) {
                    this.TIPO_IDENTIFICACIONField = value;
                    this.RaisePropertyChanged("TIPO_IDENTIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TIPO_IDENTIFICACION_ID {
            get {
                return this.TIPO_IDENTIFICACION_IDField;
            }
            set {
                if ((this.TIPO_IDENTIFICACION_IDField.Equals(value) != true)) {
                    this.TIPO_IDENTIFICACION_IDField = value;
                    this.RaisePropertyChanged("TIPO_IDENTIFICACION_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_MODULOS_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_MODULOS_USUARIO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_MODULOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_MODULO {
            get {
                return this.ID_MODULOField;
            }
            set {
                if ((this.ID_MODULOField.Equals(value) != true)) {
                    this.ID_MODULOField = value;
                    this.RaisePropertyChanged("ID_MODULO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_PERFILES_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_PERFILES_USUARIO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_PERFILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_PERFIL_PADREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PRIORIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((this.ESTADOField.Equals(value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_PERFIL {
            get {
                return this.ID_PERFILField;
            }
            set {
                if ((this.ID_PERFILField.Equals(value) != true)) {
                    this.ID_PERFILField = value;
                    this.RaisePropertyChanged("ID_PERFIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_PERFIL_PADRE {
            get {
                return this.ID_PERFIL_PADREField;
            }
            set {
                if ((this.ID_PERFIL_PADREField.Equals(value) != true)) {
                    this.ID_PERFIL_PADREField = value;
                    this.RaisePropertyChanged("ID_PERFIL_PADRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PRIORIDAD {
            get {
                return this.PRIORIDADField;
            }
            set {
                if ((this.PRIORIDADField.Equals(value) != true)) {
                    this.PRIORIDADField = value;
                    this.RaisePropertyChanged("PRIORIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_MENUS_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_MENUS_USUARIO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ABREVIACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENLACEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ICONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_MENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_MENU_PADREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_MODULOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ORDENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PRIORIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITULOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ABREVIACION {
            get {
                return this.ABREVIACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ABREVIACIONField, value) != true)) {
                    this.ABREVIACIONField = value;
                    this.RaisePropertyChanged("ABREVIACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENLACE {
            get {
                return this.ENLACEField;
            }
            set {
                if ((object.ReferenceEquals(this.ENLACEField, value) != true)) {
                    this.ENLACEField = value;
                    this.RaisePropertyChanged("ENLACE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ICONO {
            get {
                return this.ICONOField;
            }
            set {
                if ((object.ReferenceEquals(this.ICONOField, value) != true)) {
                    this.ICONOField = value;
                    this.RaisePropertyChanged("ICONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_MENU {
            get {
                return this.ID_MENUField;
            }
            set {
                if ((this.ID_MENUField.Equals(value) != true)) {
                    this.ID_MENUField = value;
                    this.RaisePropertyChanged("ID_MENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_MENU_PADRE {
            get {
                return this.ID_MENU_PADREField;
            }
            set {
                if ((this.ID_MENU_PADREField.Equals(value) != true)) {
                    this.ID_MENU_PADREField = value;
                    this.RaisePropertyChanged("ID_MENU_PADRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_MODULO {
            get {
                return this.ID_MODULOField;
            }
            set {
                if ((this.ID_MODULOField.Equals(value) != true)) {
                    this.ID_MODULOField = value;
                    this.RaisePropertyChanged("ID_MODULO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ORDEN {
            get {
                return this.ORDENField;
            }
            set {
                if ((this.ORDENField.Equals(value) != true)) {
                    this.ORDENField = value;
                    this.RaisePropertyChanged("ORDEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PRIORIDAD {
            get {
                return this.PRIORIDADField;
            }
            set {
                if ((this.PRIORIDADField.Equals(value) != true)) {
                    this.PRIORIDADField = value;
                    this.RaisePropertyChanged("PRIORIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TITULO {
            get {
                return this.TITULOField;
            }
            set {
                if ((object.ReferenceEquals(this.TITULOField, value) != true)) {
                    this.TITULOField = value;
                    this.RaisePropertyChanged("TITULO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.anh.gob.bo:8443", ConfigurationName="ServicioHydroSesion.IServicioHydroSesion")]
    public interface IServicioHydroSesion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/Autenticar", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/AutenticarResponse")]
        AnhAgenteServicios.ServicioHydroSesion.O_USUARIO_CTY Autenticar(string strCredencial, string strUsuario, string strClave, ref string strMensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/AutenticarActDir", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/AutenticarActDirResponse")]
        AnhAgenteServicios.ServicioHydroSesion.O_USUARIO_CTY AutenticarActDir(string strCredencial, string autenticacion, ref string strMensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ExisteUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ExisteUsuarioResponse")]
        AnhAgenteServicios.ServicioHydroSesion.O_RESULTADO_CTY ExisteUsuario(string strCredencial, string strUsuario, ref string strMensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/RegistrarUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/RegistrarUsuarioResponse")]
        AnhAgenteServicios.ServicioHydroSesion.O_RESULTADO_CTY RegistrarUsuario(string strCredencial, string strUsuario, ref string strMensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ActivarUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ActivarUsuarioResponse")]
        AnhAgenteServicios.ServicioHydroSesion.O_RESULTADO_CTY ActivarUsuario(string strCredencial, decimal decIdUsuario, ref string strMensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerUsuarioResponse")]
        AnhAgenteServicios.ServicioHydroSesion.O_DETALLE_USUARIO_CTY ObtenerUsuario(string strCredencial, decimal decIdUsuario, ref string strMensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerModulosUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerModulosUsuarioRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioHydroSesion.O_MODULOS_USUARIO_CTY> ObtenerModulosUsuario(decimal decIdUsuario, string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObternerPerfilesUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObternerPerfilesUsuarioResp" +
            "onse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioHydroSesion.O_PERFILES_USUARIO_CTY> ObternerPerfilesUsuario(decimal decIdUsuario, decimal decIdModulo, string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerMenusUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerMenusUsuarioResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioHydroSesion.O_MENUS_USUARIO_CTY> ObtenerMenusUsuario(decimal decIdUsuario, decimal decIdModulo, decimal decIdPerfil, string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerMenusPerfil", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/ObtenerMenusPerfilResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioHydroSesion.O_MENUS_USUARIO_CTY> ObtenerMenusPerfil(decimal decIdPerfil, string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/CambiarClave", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/CambiarClaveResponse")]
        AnhAgenteServicios.ServicioHydroSesion.O_RESULTADO_CTY CambiarClave(decimal decIdFiltro, decimal decIdUsuario, string strClaveAnterior, string strClaveNueva, string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/AutenticarV2", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroSesion/AutenticarV2Response")]
        AnhAgenteServicios.ServicioHydroSesion.O_USUARIO_CTY AutenticarV2(string strCredencial, string strUsuario, string strClave, decimal decActualizarClave, decimal decIdModulo, ref string strMensajeError);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioHydroSesionChannel : AnhAgenteServicios.ServicioHydroSesion.IServicioHydroSesion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioHydroSesionClient : System.ServiceModel.ClientBase<AnhAgenteServicios.ServicioHydroSesion.IServicioHydroSesion>, AnhAgenteServicios.ServicioHydroSesion.IServicioHydroSesion {
        
        public ServicioHydroSesionClient() {
        }
        
        public ServicioHydroSesionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioHydroSesionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioHydroSesionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioHydroSesionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AnhAgenteServicios.ServicioHydroSesion.O_USUARIO_CTY Autenticar(string strCredencial, string strUsuario, string strClave, ref string strMensajeError) {
            return base.Channel.Autenticar(strCredencial, strUsuario, strClave, ref strMensajeError);
        }
        
        public AnhAgenteServicios.ServicioHydroSesion.O_USUARIO_CTY AutenticarActDir(string strCredencial, string autenticacion, ref string strMensajeError) {
            return base.Channel.AutenticarActDir(strCredencial, autenticacion, ref strMensajeError);
        }
        
        public AnhAgenteServicios.ServicioHydroSesion.O_RESULTADO_CTY ExisteUsuario(string strCredencial, string strUsuario, ref string strMensajeError) {
            return base.Channel.ExisteUsuario(strCredencial, strUsuario, ref strMensajeError);
        }
        
        public AnhAgenteServicios.ServicioHydroSesion.O_RESULTADO_CTY RegistrarUsuario(string strCredencial, string strUsuario, ref string strMensajeError) {
            return base.Channel.RegistrarUsuario(strCredencial, strUsuario, ref strMensajeError);
        }
        
        public AnhAgenteServicios.ServicioHydroSesion.O_RESULTADO_CTY ActivarUsuario(string strCredencial, decimal decIdUsuario, ref string strMensajeError) {
            return base.Channel.ActivarUsuario(strCredencial, decIdUsuario, ref strMensajeError);
        }
        
        public AnhAgenteServicios.ServicioHydroSesion.O_DETALLE_USUARIO_CTY ObtenerUsuario(string strCredencial, decimal decIdUsuario, ref string strMensajeError) {
            return base.Channel.ObtenerUsuario(strCredencial, decIdUsuario, ref strMensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioHydroSesion.O_MODULOS_USUARIO_CTY> ObtenerModulosUsuario(decimal decIdUsuario, string credencial, ref string mensajeError) {
            return base.Channel.ObtenerModulosUsuario(decIdUsuario, credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioHydroSesion.O_PERFILES_USUARIO_CTY> ObternerPerfilesUsuario(decimal decIdUsuario, decimal decIdModulo, string credencial, ref string mensajeError) {
            return base.Channel.ObternerPerfilesUsuario(decIdUsuario, decIdModulo, credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioHydroSesion.O_MENUS_USUARIO_CTY> ObtenerMenusUsuario(decimal decIdUsuario, decimal decIdModulo, decimal decIdPerfil, string credencial, ref string mensajeError) {
            return base.Channel.ObtenerMenusUsuario(decIdUsuario, decIdModulo, decIdPerfil, credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioHydroSesion.O_MENUS_USUARIO_CTY> ObtenerMenusPerfil(decimal decIdPerfil, string credencial, ref string mensajeError) {
            return base.Channel.ObtenerMenusPerfil(decIdPerfil, credencial, ref mensajeError);
        }
        
        public AnhAgenteServicios.ServicioHydroSesion.O_RESULTADO_CTY CambiarClave(decimal decIdFiltro, decimal decIdUsuario, string strClaveAnterior, string strClaveNueva, string credencial, ref string mensajeError) {
            return base.Channel.CambiarClave(decIdFiltro, decIdUsuario, strClaveAnterior, strClaveNueva, credencial, ref mensajeError);
        }
        
        public AnhAgenteServicios.ServicioHydroSesion.O_USUARIO_CTY AutenticarV2(string strCredencial, string strUsuario, string strClave, decimal decActualizarClave, decimal decIdModulo, ref string strMensajeError) {
            return base.Channel.AutenticarV2(strCredencial, strUsuario, strClave, decActualizarClave, decIdModulo, ref strMensajeError);
        }
    }
}
