using System;
using System.Configuration;

namespace AnhPresentacionDTEP.Parametros
{
    /// <summary>
    /// This class was generated by the CAppSettings T4 template
    /// </summary>
    public static class CAppSettings
    {
        public static string ValidationSettings_UnobtrusiveValidationMode { get { return GetConfigSettingItem("ValidationSettings:UnobtrusiveValidationMode"); } }
        public static string ServicioJson { get { return GetConfigSettingItem("ServicioJson"); } }
        public static string IdFuncionario { get { return GetConfigSettingItem("IdFuncionario"); } }
        public static string svc_obtener_tipos_operacion_act { get { return GetConfigSettingItem("svc_obtener_tipos_operacion_act"); } }
        public static string svc_listar_autorizacion_condicion { get { return GetConfigSettingItem("svc_listar_autorizacion_condicion"); } }
        public static string svc_obtener_entidades { get { return GetConfigSettingItem("svc_obtener_entidades"); } }
        public static string ServicioOctanoVolumenes { get { return GetConfigSettingItem("ServicioOctanoVolumenes"); } }
        public static string ServicioAdministradorHydro { get { return GetConfigSettingItem("ServicioAdministradorHydro"); } }
        public static string svc_WSAdministrador_EAsignaUsuarioGrupo { get { return GetConfigSettingItem("svc_WSAdministrador_EAsignaUsuarioGrupo"); } }
        public static string svc_registra_usuario_entidad_general { get { return GetConfigSettingItem("svc_registra_usuario_entidad_general"); } }
        public static string svc_WSAdministrador_ListaPerfiles { get { return GetConfigSettingItem("svc_WSAdministrador_ListaPerfiles"); } }
        public static string svc_listar_usuarios_entidad { get { return GetConfigSettingItem("svc_listar_usuarios_entidad"); } }
        public static string UrlRaiz { get { return GetConfigSettingItem("UrlRaiz"); } }
        public static string idAplicacion { get { return GetConfigSettingItem("idAplicacion"); } }
        public static string IdActividades { get { return GetConfigSettingItem("IdActividades"); } }
        public static string IdFuncionarioAnh { get { return GetConfigSettingItem("IdFuncionarioAnh"); } }
        public static string IdRegulado { get { return GetConfigSettingItem("IdRegulado"); } }
        public static string IdPerfilAdministradorHydro { get { return GetConfigSettingItem("IdPerfilAdministradorHydro"); } }
        public static string LinkCrearCuenta { get { return GetConfigSettingItem("LinkCrearCuenta"); } }
        public static string LinkSireHydro { get { return GetConfigSettingItem("LinkSireHydro"); } }
        public static string idImportadores { get { return GetConfigSettingItem("idImportadores"); } }
        public static string idTerminalesAlmacenaje { get { return GetConfigSettingItem("idTerminalesAlmacenaje"); } }
        public static string idIndustrializacion { get { return GetConfigSettingItem("idIndustrializacion"); } }
        public static string idRefinacion { get { return GetConfigSettingItem("idRefinacion"); } }
        public static string idProcGasNatEnCampo { get { return GetConfigSettingItem("idProcGasNatEnCampo"); } }
        public static string idAeropuerto { get { return GetConfigSettingItem("idAeropuerto"); } }
        public static string idEntorno { get { return GetConfigSettingItem("idEntorno"); } }
        public static string UrlWSInfraestructura { get { return GetConfigSettingItem("UrlWSInfraestructura"); } }
        public static string ServicioJsonSeguridad { get { return GetConfigSettingItem("ServicioJsonSeguridad"); } }
        public static string accionTraza { get { return GetConfigSettingItem("accionTraza"); } }
        public static string notificarCorreo { get { return GetConfigSettingItem("notificarCorreo"); } }
        public static string rutaArchivoTraza { get { return GetConfigSettingItem("rutaArchivoTraza"); } }
        public static string nombreArchivoTraza { get { return GetConfigSettingItem("nombreArchivoTraza"); } }
        public static string tamanioArchivo { get { return GetConfigSettingItem("tamanioArchivo"); } }
    
        private const string MISSING_CONFIG = "Invalid configuration. Required AppSettings section is missing";
        private const string INVALID_CONFIG_SETTING = "Invalid configuration setting name: {0}";

        private static string GetConfigSettingItem(string name)
        {
            if (ConfigurationManager.AppSettings == null)
                throw new ConfigurationErrorsException(MISSING_CONFIG);

            string value = null;
            if (ConfigurationManager.AppSettings.Count != 0)
            {
                try
                {
                    value = ConfigurationManager.AppSettings.Get(name);
                }
                catch (Exception exception)
                {
                    throw new ConfigurationErrorsException(SettingItemErrorMessage(name, exception));
                }
            }
            return value;
        }
        
        private static string SettingItemErrorMessage(string name)
        {
            return string.Format(INVALID_CONFIG_SETTING, name);
        }

        private static string SettingItemErrorMessage(string name, Exception exception)
        {
            return string.Format(INVALID_CONFIG_SETTING, name) + exception.Message;
        }
    }
}
