//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhAgenteServicios.ServicioParametricas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_PARAMETRICA_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_PARAMETRICA_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_PARAMETRICA_DOCUMENTOS_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_PARAMETRICA_DOCUMENTOS_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_PADREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIGLAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOField, value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_PADRE {
            get {
                return this.ID_PADREField;
            }
            set {
                if ((this.ID_PADREField.Equals(value) != true)) {
                    this.ID_PADREField = value;
                    this.RaisePropertyChanged("ID_PADRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SIGLA {
            get {
                return this.SIGLAField;
            }
            set {
                if ((object.ReferenceEquals(this.SIGLAField, value) != true)) {
                    this.SIGLAField = value;
                    this.RaisePropertyChanged("SIGLA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_ORGANIGRAMAS_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_ORGANIGRAMAS_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NIVELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIGLAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NIVEL {
            get {
                return this.NIVELField;
            }
            set {
                if ((this.NIVELField.Equals(value) != true)) {
                    this.NIVELField = value;
                    this.RaisePropertyChanged("NIVEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SIGLA {
            get {
                return this.SIGLAField;
            }
            set {
                if ((object.ReferenceEquals(this.SIGLAField, value) != true)) {
                    this.SIGLAField = value;
                    this.RaisePropertyChanged("SIGLA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_UBICACIONES_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_UBICACIONES_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ABREVIACION2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ABREVIACION3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_IDENTIFICADORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ABREVIACION2 {
            get {
                return this.ABREVIACION2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ABREVIACION2Field, value) != true)) {
                    this.ABREVIACION2Field = value;
                    this.RaisePropertyChanged("ABREVIACION2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ABREVIACION3 {
            get {
                return this.ABREVIACION3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ABREVIACION3Field, value) != true)) {
                    this.ABREVIACION3Field = value;
                    this.RaisePropertyChanged("ABREVIACION3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_IDENTIFICADOR {
            get {
                return this.ID_IDENTIFICADORField;
            }
            set {
                if ((this.ID_IDENTIFICADORField.Equals(value) != true)) {
                    this.ID_IDENTIFICADORField = value;
                    this.RaisePropertyChanged("ID_IDENTIFICADOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_UBICACION_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_UBICACION_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ABREVIACION2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ABREVIACION3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_GEOGRAFICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_UBICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_TIPO_UBICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_UBICACION_ANTERIORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_UBICACION_GEOGRAFICAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_UBICACION_GEOGRAFIC_PADREField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ABREVIACION2 {
            get {
                return this.ABREVIACION2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ABREVIACION2Field, value) != true)) {
                    this.ABREVIACION2Field = value;
                    this.RaisePropertyChanged("ABREVIACION2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ABREVIACION3 {
            get {
                return this.ABREVIACION3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ABREVIACION3Field, value) != true)) {
                    this.ABREVIACION3Field = value;
                    this.RaisePropertyChanged("ABREVIACION3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_GEOGRAFICO {
            get {
                return this.CODIGO_GEOGRAFICOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_GEOGRAFICOField, value) != true)) {
                    this.CODIGO_GEOGRAFICOField = value;
                    this.RaisePropertyChanged("CODIGO_GEOGRAFICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_UBICACION {
            get {
                return this.CODIGO_UBICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_UBICACIONField, value) != true)) {
                    this.CODIGO_UBICACIONField = value;
                    this.RaisePropertyChanged("CODIGO_UBICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_TIPO_UBICACION {
            get {
                return this.ID_TIPO_UBICACIONField;
            }
            set {
                if ((this.ID_TIPO_UBICACIONField.Equals(value) != true)) {
                    this.ID_TIPO_UBICACIONField = value;
                    this.RaisePropertyChanged("ID_TIPO_UBICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_UBICACION_ANTERIOR {
            get {
                return this.ID_UBICACION_ANTERIORField;
            }
            set {
                if ((this.ID_UBICACION_ANTERIORField.Equals(value) != true)) {
                    this.ID_UBICACION_ANTERIORField = value;
                    this.RaisePropertyChanged("ID_UBICACION_ANTERIOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_UBICACION_GEOGRAFICA {
            get {
                return this.ID_UBICACION_GEOGRAFICAField;
            }
            set {
                if ((this.ID_UBICACION_GEOGRAFICAField.Equals(value) != true)) {
                    this.ID_UBICACION_GEOGRAFICAField = value;
                    this.RaisePropertyChanged("ID_UBICACION_GEOGRAFICA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_UBICACION_GEOGRAFIC_PADRE {
            get {
                return this.ID_UBICACION_GEOGRAFIC_PADREField;
            }
            set {
                if ((this.ID_UBICACION_GEOGRAFIC_PADREField.Equals(value) != true)) {
                    this.ID_UBICACION_GEOGRAFIC_PADREField = value;
                    this.RaisePropertyChanged("ID_UBICACION_GEOGRAFIC_PADRE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_UBICACION_GEO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_UBICACION_GEO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ABREVIACION2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ABREVIACION3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_GEOGRAFICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_UBICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_TIPO_UBICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_UBICACION_ANTERIORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_UBICACION_GEOGRAFICAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_UBICACION_GEOGRAFIC_PADREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LEVELField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ABREVIACION2 {
            get {
                return this.ABREVIACION2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ABREVIACION2Field, value) != true)) {
                    this.ABREVIACION2Field = value;
                    this.RaisePropertyChanged("ABREVIACION2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ABREVIACION3 {
            get {
                return this.ABREVIACION3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ABREVIACION3Field, value) != true)) {
                    this.ABREVIACION3Field = value;
                    this.RaisePropertyChanged("ABREVIACION3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_GEOGRAFICO {
            get {
                return this.CODIGO_GEOGRAFICOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_GEOGRAFICOField, value) != true)) {
                    this.CODIGO_GEOGRAFICOField = value;
                    this.RaisePropertyChanged("CODIGO_GEOGRAFICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_UBICACION {
            get {
                return this.CODIGO_UBICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_UBICACIONField, value) != true)) {
                    this.CODIGO_UBICACIONField = value;
                    this.RaisePropertyChanged("CODIGO_UBICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_TIPO_UBICACION {
            get {
                return this.ID_TIPO_UBICACIONField;
            }
            set {
                if ((this.ID_TIPO_UBICACIONField.Equals(value) != true)) {
                    this.ID_TIPO_UBICACIONField = value;
                    this.RaisePropertyChanged("ID_TIPO_UBICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_UBICACION_ANTERIOR {
            get {
                return this.ID_UBICACION_ANTERIORField;
            }
            set {
                if ((this.ID_UBICACION_ANTERIORField.Equals(value) != true)) {
                    this.ID_UBICACION_ANTERIORField = value;
                    this.RaisePropertyChanged("ID_UBICACION_ANTERIOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_UBICACION_GEOGRAFICA {
            get {
                return this.ID_UBICACION_GEOGRAFICAField;
            }
            set {
                if ((this.ID_UBICACION_GEOGRAFICAField.Equals(value) != true)) {
                    this.ID_UBICACION_GEOGRAFICAField = value;
                    this.RaisePropertyChanged("ID_UBICACION_GEOGRAFICA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_UBICACION_GEOGRAFIC_PADRE {
            get {
                return this.ID_UBICACION_GEOGRAFIC_PADREField;
            }
            set {
                if ((this.ID_UBICACION_GEOGRAFIC_PADREField.Equals(value) != true)) {
                    this.ID_UBICACION_GEOGRAFIC_PADREField = value;
                    this.RaisePropertyChanged("ID_UBICACION_GEOGRAFIC_PADRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LEVEL {
            get {
                return this.LEVELField;
            }
            set {
                if ((this.LEVELField.Equals(value) != true)) {
                    this.LEVELField = value;
                    this.RaisePropertyChanged("LEVEL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_DATOS_FECHAS_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_DATOS_FECHAS_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DIAS_CALENDARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DIAS_HABILESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_FINALIZACIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DIAS_CALENDARIO {
            get {
                return this.DIAS_CALENDARIOField;
            }
            set {
                if ((this.DIAS_CALENDARIOField.Equals(value) != true)) {
                    this.DIAS_CALENDARIOField = value;
                    this.RaisePropertyChanged("DIAS_CALENDARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DIAS_HABILES {
            get {
                return this.DIAS_HABILESField;
            }
            set {
                if ((this.DIAS_HABILESField.Equals(value) != true)) {
                    this.DIAS_HABILESField = value;
                    this.RaisePropertyChanged("DIAS_HABILES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA_FINALIZACION {
            get {
                return this.FECHA_FINALIZACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_FINALIZACIONField, value) != true)) {
                    this.FECHA_FINALIZACIONField = value;
                    this.RaisePropertyChanged("FECHA_FINALIZACION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.anh.gob.bo:8443", ConfigurationName="ServicioParametricas.IServicioParametricas")]
    public interface IServicioParametricas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoAmbitosOperacion", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoAmbitosOperacionRes" +
            "ponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoAmbitosOperacion(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoAseguradoras", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoAseguradorasRespons" +
            "e")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoAseguradoras(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoBancos", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoBancosResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoBancos(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCargos", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCargosResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCargos(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCategoriasActividad" +
            "", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCategoriasActividad" +
            "Response")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCategoriasActividad(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCategoriasLicCond", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCategoriasLicCondRe" +
            "sponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCategoriasLicCond(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCategoriasTramite", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCategoriasTramiteRe" +
            "sponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCategoriasTramite(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCategoriasVehiculo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCategoriasVehiculoR" +
            "esponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCategoriasVehiculo(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCatInstaladoras", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoCatInstaladorasResp" +
            "onse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCatInstaladoras(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoClasesVehiculo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoClasesVehiculoRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoClasesVehiculo(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoColegiosContadores", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoColegiosContadoresR" +
            "esponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoColegiosContadores(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoColoresVehiculo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoColoresVehiculoResp" +
            "onse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoColoresVehiculo(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoDepartamentos", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoDepartamentosRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoDepartamentos(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoDirecciones", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoDireccionesResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoDirecciones(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoEstadosCiviles", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoEstadosCivilesRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoEstadosCiviles(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoEstadosInforme", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoEstadosInformeRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoEstadosInforme(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoEstadosKardex", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoEstadosKardexRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoEstadosKardex(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoEstadosProceso", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoEstadosProcesoRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoEstadosProceso(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoGeneros", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoGenerosResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoGeneros(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoGestiones", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoGestionesResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoGestiones(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoHidrocarburos", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoHidrocarburosRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoHidrocarburos(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoInspectores", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoInspectoresResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoInspectores(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoLocalidades", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoLocalidadesResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoLocalidades(string credencial, decimal idProvincia, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoMarcasCilindro", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoMarcasCilindroRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoMarcasCilindro(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoMarcasKit", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoMarcasKitResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoMarcasKit(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoMarcasVehiculo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoMarcasVehiculoRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoMarcasVehiculo(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoMunicipios", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoMunicipiosResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoMunicipios(string credencial, decimal decIdProvincia, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoPaises", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoPaisesResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoPaises(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoPlantas", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoPlantasResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoPlantas(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoPreciosDidrocarburo" +
            "", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoPreciosDidrocarburo" +
            "Response")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoPreciosDidrocarburo(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoPrioridades", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoPrioridadesResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoPrioridades(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoProvincias", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoProvinciasResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoProvincias(string credencial, decimal idDepartamento, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoRegionesGeograficas" +
            "", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoRegionesGeograficas" +
            "Response")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoRegionesGeograficas(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoRequisitosGPS", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoRequisitosGPSRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoRequisitosGPS(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoServiciosVehiculo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoServiciosVehiculoRe" +
            "sponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoServiciosVehiculo(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposActividad", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposActividadRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposActividad(string credencial, decimal idCategoriaActividad, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposCertificado", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposCertificadoRes" +
            "ponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposCertificado(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposCobertura", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposCoberturaRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposCobertura(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposCopia", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposCopiaResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposCopia(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposDocumento", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposDocumentoRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_DOCUMENTOS_CTY> listadoTiposDocumento(string credencial, decimal decIdPadre, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposDocInscr", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposDocInscrRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposDocInscr(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposDocVehiculo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposDocVehiculoRes" +
            "ponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposDocVehiculo(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposEntidad", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposEntidadRespons" +
            "e")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposEntidad(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposEnvio", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposEnvioResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposEnvio(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposFuncion", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposFuncionRespons" +
            "e")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposFuncion(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposIdentificacion" +
            "", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposIdentificacion" +
            "Response")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposIdentificacion(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposImagen", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposImagenResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposImagen(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposInforme", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposInformeRespons" +
            "e")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposInforme(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposLicencia", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposLicenciaRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposLicencia(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposParentesco", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposParentescoResp" +
            "onse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposParentesco(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposPoliza", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposPolizaResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposPoliza(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposPropietario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposPropietarioRes" +
            "ponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposPropietario(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposRepresentante", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposRepresentanteR" +
            "esponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposRepresentante(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposSangre", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposSangreResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposSangre(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposSociedad", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposSociedadRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposSociedad(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposSucursal", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposSucursalRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposSucursal(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposTanque", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposTanqueResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposTanque(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposTramite", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposTramiteRespons" +
            "e")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposTramite(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposTransporte", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposTransporteResp" +
            "onse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposTransporte(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposVehiculo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoTiposVehiculoRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposVehiculo(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoUnidad", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoUnidadResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoUnidad(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoUnidades", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoUnidadesResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoUnidades(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadClasificacionCargo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadClasificacionCargoRe" +
            "sponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadClasificacionCargo(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadCondicionesLaborales" +
            "", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadCondicionesLaborales" +
            "Response")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadCondicionesLaborales(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoOrganigrama", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoOrganigramaResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_ORGANIGRAMAS_CTY> listadoOrganigrama(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoClasesMaquinaria", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoClasesMaquinariaRes" +
            "ponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoClasesMaquinaria(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoMarcasMaquinaria", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/listadoMarcasMaquinariaRes" +
            "ponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoMarcasMaquinaria(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/ListadoActividadesEconomic" +
            "as", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/ListadoActividadesEconomic" +
            "asResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> ListadoActividadesEconomicas(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/ListadoCategoriaFotoPerson" +
            "a", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/ListadoCategoriaFotoPerson" +
            "aResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> ListadoCategoriaFotoPersona(string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/ObtieneDescripcionGeografi" +
            "ca", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/ObtieneDescripcionGeografi" +
            "caResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_UBICACIONES_CTY> ObtieneDescripcionGeografica(string strCredencial, decimal decIdIdentificador, decimal decTipoConsulta, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/ListaUbicacionGeografica", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/ListaUbicacionGeograficaRe" +
            "sponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_UBICACION_CTY> ListaUbicacionGeografica(string strCredencial, decimal decNivel, decimal decIdPadre, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/ObtieneUbicacionGeografica" +
            "", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/ObtieneUbicacionGeografica" +
            "Response")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_UBICACION_GEO_CTY> ObtieneUbicacionGeografica(string strCredencial, decimal decIdentificador, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioParametricas/ObtieneFechaLimite", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioParametricas/ObtieneFechaLimiteResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_DATOS_FECHAS_CTY> ObtieneFechaLimite(decimal decFechaInicial, decimal decFechaFinal, decimal decDias, decimal decIdDepartamento, string strCredencialHydro, ref string mensajeError);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioParametricasChannel : AnhAgenteServicios.ServicioParametricas.IServicioParametricas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioParametricasClient : System.ServiceModel.ClientBase<AnhAgenteServicios.ServicioParametricas.IServicioParametricas>, AnhAgenteServicios.ServicioParametricas.IServicioParametricas {
        
        public ServicioParametricasClient() {
        }
        
        public ServicioParametricasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioParametricasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioParametricasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioParametricasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoAmbitosOperacion(string credencial, ref string mensajeError) {
            return base.Channel.listadoAmbitosOperacion(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoAseguradoras(string credencial, ref string mensajeError) {
            return base.Channel.listadoAseguradoras(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoBancos(string credencial, ref string mensajeError) {
            return base.Channel.listadoBancos(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCargos(string credencial, ref string mensajeError) {
            return base.Channel.listadoCargos(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCategoriasActividad(string credencial, ref string mensajeError) {
            return base.Channel.listadoCategoriasActividad(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCategoriasLicCond(string credencial, ref string mensajeError) {
            return base.Channel.listadoCategoriasLicCond(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCategoriasTramite(string credencial, ref string mensajeError) {
            return base.Channel.listadoCategoriasTramite(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCategoriasVehiculo(string credencial, ref string mensajeError) {
            return base.Channel.listadoCategoriasVehiculo(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoCatInstaladoras(string credencial, ref string mensajeError) {
            return base.Channel.listadoCatInstaladoras(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoClasesVehiculo(string credencial, ref string mensajeError) {
            return base.Channel.listadoClasesVehiculo(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoColegiosContadores(string credencial, ref string mensajeError) {
            return base.Channel.listadoColegiosContadores(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoColoresVehiculo(string credencial, ref string mensajeError) {
            return base.Channel.listadoColoresVehiculo(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoDepartamentos(string credencial, ref string mensajeError) {
            return base.Channel.listadoDepartamentos(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoDirecciones(string credencial, ref string mensajeError) {
            return base.Channel.listadoDirecciones(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoEstadosCiviles(string credencial, ref string mensajeError) {
            return base.Channel.listadoEstadosCiviles(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoEstadosInforme(string credencial, ref string mensajeError) {
            return base.Channel.listadoEstadosInforme(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoEstadosKardex(string credencial, ref string mensajeError) {
            return base.Channel.listadoEstadosKardex(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoEstadosProceso(string credencial, ref string mensajeError) {
            return base.Channel.listadoEstadosProceso(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoGeneros(string credencial, ref string mensajeError) {
            return base.Channel.listadoGeneros(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoGestiones(string credencial, ref string mensajeError) {
            return base.Channel.listadoGestiones(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoHidrocarburos(string credencial, ref string mensajeError) {
            return base.Channel.listadoHidrocarburos(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoInspectores(string credencial, ref string mensajeError) {
            return base.Channel.listadoInspectores(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoLocalidades(string credencial, decimal idProvincia, ref string mensajeError) {
            return base.Channel.listadoLocalidades(credencial, idProvincia, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoMarcasCilindro(string credencial, ref string mensajeError) {
            return base.Channel.listadoMarcasCilindro(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoMarcasKit(string credencial, ref string mensajeError) {
            return base.Channel.listadoMarcasKit(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoMarcasVehiculo(string credencial, ref string mensajeError) {
            return base.Channel.listadoMarcasVehiculo(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoMunicipios(string credencial, decimal decIdProvincia, ref string mensajeError) {
            return base.Channel.listadoMunicipios(credencial, decIdProvincia, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoPaises(string credencial, ref string mensajeError) {
            return base.Channel.listadoPaises(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoPlantas(string credencial, ref string mensajeError) {
            return base.Channel.listadoPlantas(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoPreciosDidrocarburo(string credencial, ref string mensajeError) {
            return base.Channel.listadoPreciosDidrocarburo(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoPrioridades(string credencial, ref string mensajeError) {
            return base.Channel.listadoPrioridades(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoProvincias(string credencial, decimal idDepartamento, ref string mensajeError) {
            return base.Channel.listadoProvincias(credencial, idDepartamento, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoRegionesGeograficas(string credencial, ref string mensajeError) {
            return base.Channel.listadoRegionesGeograficas(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoRequisitosGPS(string credencial, ref string mensajeError) {
            return base.Channel.listadoRequisitosGPS(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoServiciosVehiculo(string credencial, ref string mensajeError) {
            return base.Channel.listadoServiciosVehiculo(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposActividad(string credencial, decimal idCategoriaActividad, ref string mensajeError) {
            return base.Channel.listadoTiposActividad(credencial, idCategoriaActividad, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposCertificado(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposCertificado(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposCobertura(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposCobertura(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposCopia(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposCopia(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_DOCUMENTOS_CTY> listadoTiposDocumento(string credencial, decimal decIdPadre, ref string mensajeError) {
            return base.Channel.listadoTiposDocumento(credencial, decIdPadre, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposDocInscr(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposDocInscr(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposDocVehiculo(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposDocVehiculo(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposEntidad(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposEntidad(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposEnvio(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposEnvio(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposFuncion(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposFuncion(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposIdentificacion(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposIdentificacion(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposImagen(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposImagen(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposInforme(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposInforme(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposLicencia(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposLicencia(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposParentesco(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposParentesco(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposPoliza(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposPoliza(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposPropietario(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposPropietario(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposRepresentante(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposRepresentante(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposSangre(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposSangre(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposSociedad(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposSociedad(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposSucursal(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposSucursal(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposTanque(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposTanque(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposTramite(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposTramite(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposTransporte(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposTransporte(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoTiposVehiculo(string credencial, ref string mensajeError) {
            return base.Channel.listadoTiposVehiculo(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoUnidad(string credencial, ref string mensajeError) {
            return base.Channel.listadoUnidad(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoUnidades(string credencial, ref string mensajeError) {
            return base.Channel.listadoUnidades(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadClasificacionCargo(string credencial, ref string mensajeError) {
            return base.Channel.listadClasificacionCargo(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadCondicionesLaborales(string credencial, ref string mensajeError) {
            return base.Channel.listadCondicionesLaborales(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_ORGANIGRAMAS_CTY> listadoOrganigrama(string credencial, ref string mensajeError) {
            return base.Channel.listadoOrganigrama(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoClasesMaquinaria(string credencial, ref string mensajeError) {
            return base.Channel.listadoClasesMaquinaria(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> listadoMarcasMaquinaria(string credencial, ref string mensajeError) {
            return base.Channel.listadoMarcasMaquinaria(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> ListadoActividadesEconomicas(string credencial, ref string mensajeError) {
            return base.Channel.ListadoActividadesEconomicas(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_PARAMETRICA_CTY> ListadoCategoriaFotoPersona(string credencial, ref string mensajeError) {
            return base.Channel.ListadoCategoriaFotoPersona(credencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_UBICACIONES_CTY> ObtieneDescripcionGeografica(string strCredencial, decimal decIdIdentificador, decimal decTipoConsulta, ref string mensajeError) {
            return base.Channel.ObtieneDescripcionGeografica(strCredencial, decIdIdentificador, decTipoConsulta, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_UBICACION_CTY> ListaUbicacionGeografica(string strCredencial, decimal decNivel, decimal decIdPadre, ref string mensajeError) {
            return base.Channel.ListaUbicacionGeografica(strCredencial, decNivel, decIdPadre, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_UBICACION_GEO_CTY> ObtieneUbicacionGeografica(string strCredencial, decimal decIdentificador, ref string mensajeError) {
            return base.Channel.ObtieneUbicacionGeografica(strCredencial, decIdentificador, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioParametricas.O_DATOS_FECHAS_CTY> ObtieneFechaLimite(decimal decFechaInicial, decimal decFechaFinal, decimal decDias, decimal decIdDepartamento, string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ObtieneFechaLimite(decFechaInicial, decFechaFinal, decDias, decIdDepartamento, strCredencialHydro, ref mensajeError);
        }
    }
}
