//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class LISTA_TANQUE_ENTIDAD
    {
        public string CODIGO { get; set; }
        public decimal VOLUMEN_MAXIMO { get; set; }
        public decimal VOLUMEN_NETO { get; set; }
        public decimal VOLUMEN_NOMINAL { get; set; }
        public string ESTADO_VIGENCIA { get; set; }
        public decimal DIAMETRO { get; set; }
        public decimal ALTURA { get; set; }
        public string CODIGO_PRODUCTO { get; set; }
        public decimal UBICACION_GIS_NORTE { get; set; }
        public decimal UBICACION_GIS_ESTE { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO_ACTIVIDAD { get; set; }
        public string TIPO_TANQUE { get; set; }
        public string TIPO_TECHO { get; set; }
        public decimal RESULTADO { get; set; }
        public string MENSAJE_ERROR { get; set; }
    }
}
