//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class LISTA_PRUEBAS_CALIDAD
    {
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION_PRUEBA { get; set; }
        public string PRUEBA_CALIDAD_PADRE { get; set; }
        public Nullable<decimal> ESPEC_MINIMA { get; set; }
        public Nullable<decimal> ESPEC_MAXIMA { get; set; }
        public string ESPEC_ALFANUMERICO { get; set; }
        public string CODIGO_UNIDAD_MEDIDA { get; set; }
        public string TIPO_PRUEBA { get; set; }
        public string DESCRIPCION_UNIDAD { get; set; }
        public string TIPO_TEMPORADA { get; set; }
        public string TIPO_UBICACION { get; set; }
        public string TIPO_RANGO_INTERMEDIO { get; set; }
        public string TIPO_VALOR_REFERENCIA { get; set; }
        public decimal RESULTADO { get; set; }
        public string MENSAJE_ERROR { get; set; }
    }
}
