//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_CERTIFICADO_ALERTAS_CTY
    {
        public string DESCRIPCION { get; set; }
        public decimal ID_REGISTRO_CALIDAD { get; set; }
        public string VALOR_ALFANUMERICO { get; set; }
        public string ID_METODO_ASTM { get; set; }
        public string ASTM { get; set; }
        public decimal ID_PRUEBA_UNIDAD { get; set; }
        public Nullable<decimal> PU_MIN { get; set; }
        public Nullable<decimal> PU_MAX { get; set; }
        public string PU_ALFA { get; set; }
        public decimal ID_UNIDAD_MEDIDA { get; set; }
        public string UNIDAD_MEDIDA { get; set; }
        public Nullable<decimal> ID_REGISTRO_ALERTA { get; set; }
        public string OBSERVACION { get; set; }
    }
}
