//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_LISTA_DOCUMENTOS_CTY
    {
        public decimal ID_DOCUMENTO { get; set; }
        public decimal ID_TIPO_RESPALDO { get; set; }
        public string RESPALDO { get; set; }
        public byte[] DOCUMENTO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string OBSERVACION { get; set; }
        public string CITE { get; set; }
    }
}
