//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_LISTA_ENTIDAD_PROP_CTY
    {
        public decimal ID_ENTIDAD { get; set; }
        public string ENTIDAD { get; set; }
        public decimal ID_TIPO_ACTIVIDAD { get; set; }
        public string TIPO_ACTIVIDAD { get; set; }
    }
}
