//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_LISTA_CAMPO_ENTIDAD_CTY
    {
        public Nullable<decimal> ID_CAMPO { get; set; }
        public string NOMBRE_CAMPO { get; set; }
        public System.DateTime APP_FECHA_REGISTRO { get; set; }
        public decimal RESULTADO { get; set; }
        public string MENSAJE_ERROR { get; set; }
        public Nullable<decimal> ID_ENTIDAD { get; set; }
        public Nullable<decimal> ID_CAMPOS_ENTIDAD { get; set; }
    }
}
