//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_LISTA_PROPIETARIOS_CTY
    {
        public string CITE { get; set; }
        public decimal ID_REGISTRO_CALIDAD { get; set; }
        public decimal ID_TIPO_ACTIVIDAD { get; set; }
        public string TIPO_ACTIVIDAD { get; set; }
        public decimal ID_PROPIETARIO_CERTIFICADO { get; set; }
        public string ESTADO { get; set; }
    }
}
