//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_LISTA_PRODE_CTY
    {
        public decimal ID_PRODE { get; set; }
        public System.DateTime FECHA_PRODE { get; set; }
        public decimal VALOR_PRODE { get; set; }
        public decimal ID_ENTIDAD { get; set; }
        public Nullable<decimal> ID_CAMPO { get; set; }
        public decimal ID_UNIDAD_MEDIDA { get; set; }
        public decimal ID_TIPO_REPORTE { get; set; }
        public decimal ID_PRODUCTO { get; set; }
    }
}
