//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_LISTA_TIPO_MEDIO_TRANS_CTY
    {
        public decimal ID_TIPO_MEDIO_TRANSPORTE { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
