//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_LISTADO_MONEDA_CTY
    {
        public decimal ID_MONEDA { get; set; }
        public string CODIGO { get; set; }
        public string UNIDAD_MONETARIA { get; set; }
        public string PAIS { get; set; }
        public double TIPO_CAMBIO_BS { get; set; }
        public double ESTADO_VIGENCIA { get; set; }
        public double FECHA_DESDE { get; set; }
        public double FECHA_HASTA { get; set; }
    }
}
