//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_PRODUCTO_ESPEC_CTY
    {
        public decimal ID_TABLA_ESPEC { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
    }
}
