//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_PRUEBA_UNIDAD_CALIDAD_CTY
    {
        public string NOMBRE { get; set; }
        public decimal ID_PRUEBA_UNIDAD { get; set; }
        public decimal ID_PRUEBA_CALIDAD { get; set; }
    }
}
