//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_REPORTE_CALIDAD
    {
        public decimal ID_REGISTRO_CALIDAD { get; set; }
        public string VALOR_ALFANUMERICO { get; set; }
        public Nullable<decimal> ID_METODO_ASTM { get; set; }
        public string CODIGO_ASTM { get; set; }
        public Nullable<decimal> ID_PRUEBA_UNIDAD { get; set; }
        public Nullable<decimal> ID_UNIDAD_MEDIDA { get; set; }
        public string CODIGO_UNIDAD { get; set; }
        public Nullable<decimal> ID_TABLA_ESPEC { get; set; }
        public Nullable<decimal> ID_PRUEBA_CALIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> ORDEN { get; set; }
        public Nullable<decimal> ID_PUNTO_CUSTODIO { get; set; }
        public string PUNTO_CUSTODIO { get; set; }
        public Nullable<decimal> VOLUMEN_OP_DEBE { get; set; }
        public Nullable<decimal> ID_PRODUCTO { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<decimal> UNIDAD_MEDIDA_VOL { get; set; }
        public string CODIGO_UNIDAD_VOL { get; set; }
        public Nullable<decimal> ID_CITE { get; set; }
        public string CITE_DOCUMENTO { get; set; }
        public Nullable<decimal> ID_MEDIO_TRANSPORTE { get; set; }
        public string MEDIO_TRANSPORTE { get; set; }
        public Nullable<decimal> ID_ENTIDAD { get; set; }
        public string ENTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA_OPERACION { get; set; }
        public Nullable<System.DateTime> APP_FECHA_REGISTRO { get; set; }
        public string VALOR_LOTE { get; set; }
        public Nullable<decimal> ID_PRUEBA_CALIDAD_PADRE { get; set; }
        public string PROCEDENCIA { get; set; }
        public string TIPO_MEDIO_TRANSPORTE { get; set; }
        public Nullable<decimal> ID_TIPO_MUESTRA { get; set; }
        public string TIPO_MUESTRA { get; set; }
        public Nullable<System.DateTime> FECHA_MUESTRA { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<decimal> APP_ID_USUARIO { get; set; }
        public Nullable<decimal> VALOR_REFERENCIAL { get; set; }
        public Nullable<decimal> VOLUMEN_OP_HABER { get; set; }
        public Nullable<double> ID_RANGOS_MULTIPLES { get; set; }
        public string RANGOS_MULTIPLES { get; set; }
        public Nullable<double> VOLUMEN_OP_DEBE_MUESTRA { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public string CODIGO_IMPORTE { get; set; }
        public Nullable<double> ID_MARCA_PRODUCTO { get; set; }
        public string MARCA_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public decimal ID_ORGANIGRAMA { get; set; }
        public string PRODUCTO_PADRE { get; set; }
        public decimal ID_TIPO_ACTIVIDAD { get; set; }
        public string TIPO_ACTIVIDAD { get; set; }
        public Nullable<System.DateTime> FECHA_RA { get; set; }
        public decimal ID_ENTIDAD_DESTINO { get; set; }
        public string RUTA_INTERNACION { get; set; }
        public string EMPRESA_PROVEEDORA { get; set; }
        public string TK_ORIG_EXTERNO { get; set; }
        public string NRO_LOTE_VERIF { get; set; }
    }
}
