//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_REG_IN_REPORTE_PLANO_CTY
    {
        public string ALERTA_EMAIL { get; set; }
        public decimal CANTIDAD_ALERTAS { get; set; }
        public string CORRELATIVO_REGISTRO { get; set; }
        public string MENSAJE_ERROR { get; set; }
        public decimal RESULTADO { get; set; }
    }
}
