//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_REPORTE_REG_CALIDAD_CTY
    {
        public decimal CODIGO_CERTIFICADO_CALIDAD { get; set; }
        public string CORRELATIVO { get; set; }
        public string VALOR_PRODUCTO { get; set; }
        public decimal FECHA_OPERACION { get; set; }
        public decimal VOLUMEN { get; set; }
        public string VALOR_VOLUMEN_UNIDAD_MEDIDA { get; set; }
        public string VALOR_PUNTO_CUSTODIO { get; set; }
        public string RESOLUCION { get; set; }
        public Nullable<decimal> VOLUMEN_MUESTRA { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string CODIGO_MONEDA { get; set; }
        public string VALOR_MARCA_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public string PRUEBA_CALIDAD { get; set; }
        public string VALOR_METODO_ASTM { get; set; }
        public string VALOR_UNIDAD_MEDIDA { get; set; }
        public string VALOR_REPORTADO { get; set; }
        public string RANGOS_MULTIPLES { get; set; }
    }
}
