//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_REPORTE_CALIDAD_PRINCIPAL
    {
        public decimal ID_REGISTROCAL_PRINCIPAL { get; set; }
        public System.DateTime FECHA_OPERACION { get; set; }
        public string VALOR_LOTE { get; set; }
        public decimal ID_TABLA_ESPEC { get; set; }
        public decimal ID_CANTIDAD { get; set; }
        public Nullable<decimal> ID_MEDIO_TRANSPORTE { get; set; }
        public decimal ID_PUNTO_CUSTODIO { get; set; }
        public Nullable<decimal> ID_REGISTRO_PADRE { get; set; }
        public decimal ID_TIPO_REGISTRO { get; set; }
        public Nullable<decimal> VOLUMEN_OP_DEBE { get; set; }
        public Nullable<decimal> VOLUMEN_OP_HABER { get; set; }
        public string PUNTO_CUSTODIO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public string CODIGO_UNIDAD_MEDIDA { get; set; }
        public decimal ID_CITE { get; set; }
        public string CITE_GENERADO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public decimal ID_ENTIDAD { get; set; }
        public string ENTIDAD_DENOMINACION { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public Nullable<double> VOLUMEN_OP_DEBE_MUESTRA { get; set; }
        public Nullable<double> ID_MONEDA { get; set; }
        public string CODIGO_MONEDA { get; set; }
        public string OBSERVACIONES { get; set; }
        public string MARCA_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO_COM { get; set; }
        public string ESTADO { get; set; }
        public string OBS_DOCUMENTO { get; set; }
        public string TIPO_ACTIVIDAD { get; set; }
        public decimal ID_TIPO_ACTIVIDAD { get; set; }
        public Nullable<System.DateTime> FECHA_RA { get; set; }
        public string ENTIDAD_DEST { get; set; }
        public string RUTA_INTERNACION { get; set; }
        public string EMPRESA_PROVEEDORA { get; set; }
        public string TK_ORIG_EXTERNO { get; set; }
        public string NRO_LOTE_VERIF { get; set; }
    }
}
