//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_REF_MEDIO_TRANSPORTE_CTY
    {
        public string CODIGO { get; set; }
        public string CODIGO_BARCODE { get; set; }
        public Nullable<decimal> CODIGO_SECUNDARIO { get; set; }
        public string DESCRIPCION { get; set; }
        public string MENSAJE_ERROR { get; set; }
        public string NOMBRE { get; set; }
        public decimal RESULTADO { get; set; }
        public string TIPO_MEDIO_TRANSPORTE { get; set; }
    }
}
