//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_REPORTE_CALIDAD_PIVOTE_CTY
    {
        public decimal ID_CERTIFICADO_CALIDAD { get; set; }
        public decimal ID_REGISTRO_CALIDAD { get; set; }
        public string ENTIDAD { get; set; }
        public string ACTIVIDAD { get; set; }
        public string CORRELATIVO { get; set; }
        public string TABLA_ESPECIFICA { get; set; }
        public decimal FECHA_OPERACION { get; set; }
        public decimal VOLUMEN { get; set; }
        public string VALOR_UNIDAD_MEDIDA { get; set; }
        public string VALOR_PUNTO_CUSTODIO { get; set; }
        public string RESOLUCION { get; set; }
        public decimal FECHA_IMMU { get; set; }
        public decimal VOLUMEN_MUESTRA { get; set; }
        public decimal PRECIO { get; set; }
        public string CODIGO_MONEDA { get; set; }
        public string VALOR_MARCA_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public decimal ORDEN { get; set; }
        public string PRUEBA_CALIDAD { get; set; }
        public string VALOR_METODO_ASTM { get; set; }
        public string VALOR_UM_PRUEBA { get; set; }
        public string VALOR_REPORTADO { get; set; }
        public string RANGOS_MULTIPLES { get; set; }
        public string ALERTA { get; set; }
        public string LOTE { get; set; }
        public Nullable<System.DateTime> FECHA_RA { get; set; }
        public string ENTIDAD_DEST { get; set; }
        public string RUTA_INTERNACION { get; set; }
        public string EMPRESA_PROVEEDORA { get; set; }
        public string NRO_LOTE_VERIF { get; set; }
        public string TK_ORIG_EXTERNO { get; set; }
    }
}
