//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_RESULTADO_CTY
    {
        public decimal ID_TABLA { get; set; }
        public string MENSAJE_ERROR { get; set; }
        public Nullable<decimal> RESULTADO { get; set; }
    }
}
