//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_REPORTE_ALERTA_CERT_CTY
    {
        public decimal ID_REGISTROCAL_PRINCIPAL { get; set; }
        public System.DateTime FECHA_OPERACION { get; set; }
        public string CITE { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public string NOMBRE_COMERCIAL { get; set; }
        public string LOTE { get; set; }
        public string PTC { get; set; }
        public string RESOLUCION { get; set; }
        public decimal VOLUMEN { get; set; }
        public string UNIDAD_MEDIDA { get; set; }
        public string MARCA { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string USUARIO { get; set; }
        public string ENTIDAD { get; set; }
        public string ALERTA { get; set; }
        public string TIPO { get; set; }
    }
}
