//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_TABLA_ESPEC_FORMULARIO_CTY
    {
        public decimal ID_PRUEBA_CALIDAD { get; set; }
        public decimal ID_PRUEBA_CALIDAD_PADRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESPEC_MINIMA { get; set; }
        public string ESPEC_MAXIMA { get; set; }
        public string ESPEC_ALFANUMERICO { get; set; }
        public string UNIDAD_MEDIDA { get; set; }
        public string METODO_ASTM { get; set; }
        public string RANGOS_MULTIPLES { get; set; }
        public string ESPEC_MINIMA_RANGO { get; set; }
        public string ESPEC_MAXIMA_RANGO { get; set; }
    }
}
