//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPersistenciaCore.Core
{
    using System;
    
    public partial class O_TIPOS_ACTIVIDAD_CTY
    {
        public Nullable<decimal> ID_TIPO_ACTIVIDAD { get; set; }
        public Nullable<decimal> ID_CATEGORIA_ACTIVIDAD { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
