//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhAgenteServicios.ServicioConsultasHydro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_PERSONA_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_PERSONA_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPLEMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXPEDICIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EXPEDICION_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FECHA_NACIMIENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FECHA_REGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GENEROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GENERO_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_TIPO_IDENTIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRE_COMPLETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRIMER_APELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEGUNDO_APELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_IDENT_DESCRIPCIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CI {
            get {
                return this.CIField;
            }
            set {
                if ((object.ReferenceEquals(this.CIField, value) != true)) {
                    this.CIField = value;
                    this.RaisePropertyChanged("CI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPLEMENTO {
            get {
                return this.COMPLEMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPLEMENTOField, value) != true)) {
                    this.COMPLEMENTOField = value;
                    this.RaisePropertyChanged("COMPLEMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXPEDICION {
            get {
                return this.EXPEDICIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EXPEDICIONField, value) != true)) {
                    this.EXPEDICIONField = value;
                    this.RaisePropertyChanged("EXPEDICION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EXPEDICION_ID {
            get {
                return this.EXPEDICION_IDField;
            }
            set {
                if ((this.EXPEDICION_IDField.Equals(value) != true)) {
                    this.EXPEDICION_IDField = value;
                    this.RaisePropertyChanged("EXPEDICION_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FECHA_NACIMIENTO {
            get {
                return this.FECHA_NACIMIENTOField;
            }
            set {
                if ((this.FECHA_NACIMIENTOField.Equals(value) != true)) {
                    this.FECHA_NACIMIENTOField = value;
                    this.RaisePropertyChanged("FECHA_NACIMIENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FECHA_REGISTRO {
            get {
                return this.FECHA_REGISTROField;
            }
            set {
                if ((this.FECHA_REGISTROField.Equals(value) != true)) {
                    this.FECHA_REGISTROField = value;
                    this.RaisePropertyChanged("FECHA_REGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GENERO {
            get {
                return this.GENEROField;
            }
            set {
                if ((object.ReferenceEquals(this.GENEROField, value) != true)) {
                    this.GENEROField = value;
                    this.RaisePropertyChanged("GENERO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GENERO_ID {
            get {
                return this.GENERO_IDField;
            }
            set {
                if ((this.GENERO_IDField.Equals(value) != true)) {
                    this.GENERO_IDField = value;
                    this.RaisePropertyChanged("GENERO_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_PERSONA {
            get {
                return this.ID_PERSONAField;
            }
            set {
                if ((this.ID_PERSONAField.Equals(value) != true)) {
                    this.ID_PERSONAField = value;
                    this.RaisePropertyChanged("ID_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_TIPO_IDENTIFICACION {
            get {
                return this.ID_TIPO_IDENTIFICACIONField;
            }
            set {
                if ((this.ID_TIPO_IDENTIFICACIONField.Equals(value) != true)) {
                    this.ID_TIPO_IDENTIFICACIONField = value;
                    this.RaisePropertyChanged("ID_TIPO_IDENTIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE_COMPLETO {
            get {
                return this.NOMBRE_COMPLETOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRE_COMPLETOField, value) != true)) {
                    this.NOMBRE_COMPLETOField = value;
                    this.RaisePropertyChanged("NOMBRE_COMPLETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRIMER_APELLIDO {
            get {
                return this.PRIMER_APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRIMER_APELLIDOField, value) != true)) {
                    this.PRIMER_APELLIDOField = value;
                    this.RaisePropertyChanged("PRIMER_APELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEGUNDO_APELLIDO {
            get {
                return this.SEGUNDO_APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.SEGUNDO_APELLIDOField, value) != true)) {
                    this.SEGUNDO_APELLIDOField = value;
                    this.RaisePropertyChanged("SEGUNDO_APELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_IDENT_DESCRIPCION {
            get {
                return this.TIPO_IDENT_DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_IDENT_DESCRIPCIONField, value) != true)) {
                    this.TIPO_IDENT_DESCRIPCIONField = value;
                    this.RaisePropertyChanged("TIPO_IDENT_DESCRIPCION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_ENTIDAD_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_ENTIDAD_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FECHA_REGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_ENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SOCIEDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FECHA_REGISTRO {
            get {
                return this.FECHA_REGISTROField;
            }
            set {
                if ((this.FECHA_REGISTROField.Equals(value) != true)) {
                    this.FECHA_REGISTROField = value;
                    this.RaisePropertyChanged("FECHA_REGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_ENTIDAD {
            get {
                return this.ID_ENTIDADField;
            }
            set {
                if ((this.ID_ENTIDADField.Equals(value) != true)) {
                    this.ID_ENTIDADField = value;
                    this.RaisePropertyChanged("ID_ENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SOCIEDAD {
            get {
                return this.SOCIEDADField;
            }
            set {
                if ((object.ReferenceEquals(this.SOCIEDADField, value) != true)) {
                    this.SOCIEDADField = value;
                    this.RaisePropertyChanged("SOCIEDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_CORRELATIVO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_CORRELATIVO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CITEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_CITEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CITE {
            get {
                return this.CITEField;
            }
            set {
                if ((object.ReferenceEquals(this.CITEField, value) != true)) {
                    this.CITEField = value;
                    this.RaisePropertyChanged("CITE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_CITE {
            get {
                return this.ID_CITEField;
            }
            set {
                if ((this.ID_CITEField.Equals(value) != true)) {
                    this.ID_CITEField = value;
                    this.RaisePropertyChanged("ID_CITE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_DETALLE_VEHICULO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_DETALLE_VEHICULO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLASEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CLASE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal COLOR_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal COPIA_PLACAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MARCAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MARCA_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_CHASISField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_MOTORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PLACAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLASE {
            get {
                return this.CLASEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLASEField, value) != true)) {
                    this.CLASEField = value;
                    this.RaisePropertyChanged("CLASE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CLASE_ID {
            get {
                return this.CLASE_IDField;
            }
            set {
                if ((this.CLASE_IDField.Equals(value) != true)) {
                    this.CLASE_IDField = value;
                    this.RaisePropertyChanged("CLASE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLOR {
            get {
                return this.COLORField;
            }
            set {
                if ((object.ReferenceEquals(this.COLORField, value) != true)) {
                    this.COLORField = value;
                    this.RaisePropertyChanged("COLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal COLOR_ID {
            get {
                return this.COLOR_IDField;
            }
            set {
                if ((this.COLOR_IDField.Equals(value) != true)) {
                    this.COLOR_IDField = value;
                    this.RaisePropertyChanged("COLOR_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal COPIA_PLACA {
            get {
                return this.COPIA_PLACAField;
            }
            set {
                if ((this.COPIA_PLACAField.Equals(value) != true)) {
                    this.COPIA_PLACAField = value;
                    this.RaisePropertyChanged("COPIA_PLACA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MARCA {
            get {
                return this.MARCAField;
            }
            set {
                if ((object.ReferenceEquals(this.MARCAField, value) != true)) {
                    this.MARCAField = value;
                    this.RaisePropertyChanged("MARCA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MARCA_ID {
            get {
                return this.MARCA_IDField;
            }
            set {
                if ((this.MARCA_IDField.Equals(value) != true)) {
                    this.MARCA_IDField = value;
                    this.RaisePropertyChanged("MARCA_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_CHASIS {
            get {
                return this.NRO_CHASISField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_CHASISField, value) != true)) {
                    this.NRO_CHASISField = value;
                    this.RaisePropertyChanged("NRO_CHASIS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_MOTOR {
            get {
                return this.NRO_MOTORField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_MOTORField, value) != true)) {
                    this.NRO_MOTORField = value;
                    this.RaisePropertyChanged("NRO_MOTOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PLACA {
            get {
                return this.PLACAField;
            }
            set {
                if ((object.ReferenceEquals(this.PLACAField, value) != true)) {
                    this.PLACAField = value;
                    this.RaisePropertyChanged("PLACA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="E_VEHICULO_DATO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class E_VEHICULO_DATO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLASEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal COPIA_PLACAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_REGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_VEHICULOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MARCAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PLACAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SERVICIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TAGField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLASE {
            get {
                return this.CLASEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLASEField, value) != true)) {
                    this.CLASEField = value;
                    this.RaisePropertyChanged("CLASE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLOR {
            get {
                return this.COLORField;
            }
            set {
                if ((object.ReferenceEquals(this.COLORField, value) != true)) {
                    this.COLORField = value;
                    this.RaisePropertyChanged("COLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal COPIA_PLACA {
            get {
                return this.COPIA_PLACAField;
            }
            set {
                if ((this.COPIA_PLACAField.Equals(value) != true)) {
                    this.COPIA_PLACAField = value;
                    this.RaisePropertyChanged("COPIA_PLACA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENTIDAD {
            get {
                return this.ENTIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.ENTIDADField, value) != true)) {
                    this.ENTIDADField = value;
                    this.RaisePropertyChanged("ENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA_REGISTRO {
            get {
                return this.FECHA_REGISTROField;
            }
            set {
                if ((this.FECHA_REGISTROField.Equals(value) != true)) {
                    this.FECHA_REGISTROField = value;
                    this.RaisePropertyChanged("FECHA_REGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_VEHICULO {
            get {
                return this.ID_VEHICULOField;
            }
            set {
                if ((this.ID_VEHICULOField.Equals(value) != true)) {
                    this.ID_VEHICULOField = value;
                    this.RaisePropertyChanged("ID_VEHICULO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MARCA {
            get {
                return this.MARCAField;
            }
            set {
                if ((object.ReferenceEquals(this.MARCAField, value) != true)) {
                    this.MARCAField = value;
                    this.RaisePropertyChanged("MARCA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PLACA {
            get {
                return this.PLACAField;
            }
            set {
                if ((object.ReferenceEquals(this.PLACAField, value) != true)) {
                    this.PLACAField = value;
                    this.RaisePropertyChanged("PLACA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERVICIO {
            get {
                return this.SERVICIOField;
            }
            set {
                if ((object.ReferenceEquals(this.SERVICIOField, value) != true)) {
                    this.SERVICIOField = value;
                    this.RaisePropertyChanged("SERVICIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TAG {
            get {
                return this.TAGField;
            }
            set {
                if ((object.ReferenceEquals(this.TAGField, value) != true)) {
                    this.TAGField = value;
                    this.RaisePropertyChanged("TAG");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_PERSONA_BUSQUEDA_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_PERSONA_BUSQUEDA_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXPEDICIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FECHA_NACIMIENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GENEROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_GENEROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_TIPO_IDENTIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_COMPLEMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_IDENTIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRIMER_APELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEGUNDO_APELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TELEFONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_IDENT_DESCRIPCIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXPEDICION {
            get {
                return this.EXPEDICIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EXPEDICIONField, value) != true)) {
                    this.EXPEDICIONField = value;
                    this.RaisePropertyChanged("EXPEDICION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FECHA_NACIMIENTO {
            get {
                return this.FECHA_NACIMIENTOField;
            }
            set {
                if ((this.FECHA_NACIMIENTOField.Equals(value) != true)) {
                    this.FECHA_NACIMIENTOField = value;
                    this.RaisePropertyChanged("FECHA_NACIMIENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GENERO {
            get {
                return this.GENEROField;
            }
            set {
                if ((object.ReferenceEquals(this.GENEROField, value) != true)) {
                    this.GENEROField = value;
                    this.RaisePropertyChanged("GENERO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_DEPARTAMENTO {
            get {
                return this.ID_DEPARTAMENTOField;
            }
            set {
                if ((this.ID_DEPARTAMENTOField.Equals(value) != true)) {
                    this.ID_DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("ID_DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_GENERO {
            get {
                return this.ID_GENEROField;
            }
            set {
                if ((this.ID_GENEROField.Equals(value) != true)) {
                    this.ID_GENEROField = value;
                    this.RaisePropertyChanged("ID_GENERO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_PERSONA {
            get {
                return this.ID_PERSONAField;
            }
            set {
                if ((this.ID_PERSONAField.Equals(value) != true)) {
                    this.ID_PERSONAField = value;
                    this.RaisePropertyChanged("ID_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_TIPO_IDENTIFICACION {
            get {
                return this.ID_TIPO_IDENTIFICACIONField;
            }
            set {
                if ((this.ID_TIPO_IDENTIFICACIONField.Equals(value) != true)) {
                    this.ID_TIPO_IDENTIFICACIONField = value;
                    this.RaisePropertyChanged("ID_TIPO_IDENTIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_COMPLEMENTO {
            get {
                return this.NUMERO_COMPLEMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_COMPLEMENTOField, value) != true)) {
                    this.NUMERO_COMPLEMENTOField = value;
                    this.RaisePropertyChanged("NUMERO_COMPLEMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_IDENTIFICACION {
            get {
                return this.NUMERO_IDENTIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_IDENTIFICACIONField, value) != true)) {
                    this.NUMERO_IDENTIFICACIONField = value;
                    this.RaisePropertyChanged("NUMERO_IDENTIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRIMER_APELLIDO {
            get {
                return this.PRIMER_APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRIMER_APELLIDOField, value) != true)) {
                    this.PRIMER_APELLIDOField = value;
                    this.RaisePropertyChanged("PRIMER_APELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEGUNDO_APELLIDO {
            get {
                return this.SEGUNDO_APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.SEGUNDO_APELLIDOField, value) != true)) {
                    this.SEGUNDO_APELLIDOField = value;
                    this.RaisePropertyChanged("SEGUNDO_APELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TELEFONO {
            get {
                return this.TELEFONOField;
            }
            set {
                if ((this.TELEFONOField.Equals(value) != true)) {
                    this.TELEFONOField = value;
                    this.RaisePropertyChanged("TELEFONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_IDENT_DESCRIPCION {
            get {
                return this.TIPO_IDENT_DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_IDENT_DESCRIPCIONField, value) != true)) {
                    this.TIPO_IDENT_DESCRIPCIONField = value;
                    this.RaisePropertyChanged("TIPO_IDENT_DESCRIPCION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_FOTO_PERSONA_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_FOTO_PERSONA_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FOTOGRAFIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_CATALOG_FOTO_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_PERSONAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FOTOGRAFIA {
            get {
                return this.FOTOGRAFIAField;
            }
            set {
                if ((object.ReferenceEquals(this.FOTOGRAFIAField, value) != true)) {
                    this.FOTOGRAFIAField = value;
                    this.RaisePropertyChanged("FOTOGRAFIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_CATALOG_FOTO_PERSONA {
            get {
                return this.ID_CATALOG_FOTO_PERSONAField;
            }
            set {
                if ((this.ID_CATALOG_FOTO_PERSONAField.Equals(value) != true)) {
                    this.ID_CATALOG_FOTO_PERSONAField = value;
                    this.RaisePropertyChanged("ID_CATALOG_FOTO_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_PERSONA {
            get {
                return this.ID_PERSONAField;
            }
            set {
                if ((this.ID_PERSONAField.Equals(value) != true)) {
                    this.ID_PERSONAField = value;
                    this.RaisePropertyChanged("ID_PERSONA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_DATO_USUARIO_ANH_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_DATO_USUARIO_ANH_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_ORGANIGRAMAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_ORGANIGRAMA_DEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_COMPLEMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_IDENTIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRIMER_APELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEGUNDO_APELLIDOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_ORGANIGRAMA {
            get {
                return this.ID_ORGANIGRAMAField;
            }
            set {
                if ((this.ID_ORGANIGRAMAField.Equals(value) != true)) {
                    this.ID_ORGANIGRAMAField = value;
                    this.RaisePropertyChanged("ID_ORGANIGRAMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_ORGANIGRAMA_DEP {
            get {
                return this.ID_ORGANIGRAMA_DEPField;
            }
            set {
                if ((this.ID_ORGANIGRAMA_DEPField.Equals(value) != true)) {
                    this.ID_ORGANIGRAMA_DEPField = value;
                    this.RaisePropertyChanged("ID_ORGANIGRAMA_DEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_PERSONA {
            get {
                return this.ID_PERSONAField;
            }
            set {
                if ((this.ID_PERSONAField.Equals(value) != true)) {
                    this.ID_PERSONAField = value;
                    this.RaisePropertyChanged("ID_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_USUARIO {
            get {
                return this.ID_USUARIOField;
            }
            set {
                if ((this.ID_USUARIOField.Equals(value) != true)) {
                    this.ID_USUARIOField = value;
                    this.RaisePropertyChanged("ID_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGIN {
            get {
                return this.LOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.LOGINField, value) != true)) {
                    this.LOGINField = value;
                    this.RaisePropertyChanged("LOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_COMPLEMENTO {
            get {
                return this.NUMERO_COMPLEMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_COMPLEMENTOField, value) != true)) {
                    this.NUMERO_COMPLEMENTOField = value;
                    this.RaisePropertyChanged("NUMERO_COMPLEMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_IDENTIFICACION {
            get {
                return this.NUMERO_IDENTIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_IDENTIFICACIONField, value) != true)) {
                    this.NUMERO_IDENTIFICACIONField = value;
                    this.RaisePropertyChanged("NUMERO_IDENTIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRIMER_APELLIDO {
            get {
                return this.PRIMER_APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRIMER_APELLIDOField, value) != true)) {
                    this.PRIMER_APELLIDOField = value;
                    this.RaisePropertyChanged("PRIMER_APELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEGUNDO_APELLIDO {
            get {
                return this.SEGUNDO_APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.SEGUNDO_APELLIDOField, value) != true)) {
                    this.SEGUNDO_APELLIDOField = value;
                    this.RaisePropertyChanged("SEGUNDO_APELLIDO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_OBT_DOCUMENTO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_OBT_DOCUMENTO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_DOCUMENTO_ENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_ENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_TIPO_DOC_INSCRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_CITEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_DOCUMENTO_ENTIDAD {
            get {
                return this.ID_DOCUMENTO_ENTIDADField;
            }
            set {
                if ((this.ID_DOCUMENTO_ENTIDADField.Equals(value) != true)) {
                    this.ID_DOCUMENTO_ENTIDADField = value;
                    this.RaisePropertyChanged("ID_DOCUMENTO_ENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_ENTIDAD {
            get {
                return this.ID_ENTIDADField;
            }
            set {
                if ((this.ID_ENTIDADField.Equals(value) != true)) {
                    this.ID_ENTIDADField = value;
                    this.RaisePropertyChanged("ID_ENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_TIPO_DOC_INSCR {
            get {
                return this.ID_TIPO_DOC_INSCRField;
            }
            set {
                if ((this.ID_TIPO_DOC_INSCRField.Equals(value) != true)) {
                    this.ID_TIPO_DOC_INSCRField = value;
                    this.RaisePropertyChanged("ID_TIPO_DOC_INSCR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_CITE {
            get {
                return this.NRO_CITEField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_CITEField, value) != true)) {
                    this.NRO_CITEField = value;
                    this.RaisePropertyChanged("NRO_CITE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_OBT_USUARIO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_OBT_USUARIO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CORREOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_ENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO {
            get {
                return this.CORREOField;
            }
            set {
                if ((object.ReferenceEquals(this.CORREOField, value) != true)) {
                    this.CORREOField = value;
                    this.RaisePropertyChanged("CORREO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_ENTIDAD {
            get {
                return this.ID_ENTIDADField;
            }
            set {
                if ((this.ID_ENTIDADField.Equals(value) != true)) {
                    this.ID_ENTIDADField = value;
                    this.RaisePropertyChanged("ID_ENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_USUARIO {
            get {
                return this.ID_USUARIOField;
            }
            set {
                if ((this.ID_USUARIOField.Equals(value) != true)) {
                    this.ID_USUARIOField = value;
                    this.RaisePropertyChanged("ID_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_REPORTE_ACTIVIDAD_NAC_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_REPORTE_ACTIVIDAD_NAC_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACTIVIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CANTIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACTIVIDAD {
            get {
                return this.ACTIVIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.ACTIVIDADField, value) != true)) {
                    this.ACTIVIDADField = value;
                    this.RaisePropertyChanged("ACTIVIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CANTIDAD {
            get {
                return this.CANTIDADField;
            }
            set {
                if ((this.CANTIDADField.Equals(value) != true)) {
                    this.CANTIDADField = value;
                    this.RaisePropertyChanged("CANTIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_OBTIENE_ENTIDADES_ACT_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_OBTIENE_ENTIDADES_ACT_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DENOMINACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ENTIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DENOMINACION {
            get {
                return this.DENOMINACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DENOMINACIONField, value) != true)) {
                    this.DENOMINACIONField = value;
                    this.RaisePropertyChanged("DENOMINACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DEPARTAMENTO {
            get {
                return this.ID_DEPARTAMENTOField;
            }
            set {
                if ((this.ID_DEPARTAMENTOField.Equals(value) != true)) {
                    this.ID_DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("ID_DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ENTIDAD {
            get {
                return this.ID_ENTIDADField;
            }
            set {
                if ((this.ID_ENTIDADField.Equals(value) != true)) {
                    this.ID_ENTIDADField = value;
                    this.RaisePropertyChanged("ID_ENTIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_EMISION_PERIODO_CERT_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_EMISION_PERIODO_CERT_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CANTIDAD_CERTIFICADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MUNICIPIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERIODOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CANTIDAD_CERTIFICADO {
            get {
                return this.CANTIDAD_CERTIFICADOField;
            }
            set {
                if ((this.CANTIDAD_CERTIFICADOField.Equals(value) != true)) {
                    this.CANTIDAD_CERTIFICADOField = value;
                    this.RaisePropertyChanged("CANTIDAD_CERTIFICADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPARTAMENTO {
            get {
                return this.DEPARTAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPARTAMENTOField, value) != true)) {
                    this.DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MUNICIPIO {
            get {
                return this.MUNICIPIOField;
            }
            set {
                if ((object.ReferenceEquals(this.MUNICIPIOField, value) != true)) {
                    this.MUNICIPIOField = value;
                    this.RaisePropertyChanged("MUNICIPIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERIODO {
            get {
                return this.PERIODOField;
            }
            set {
                if ((object.ReferenceEquals(this.PERIODOField, value) != true)) {
                    this.PERIODOField = value;
                    this.RaisePropertyChanged("PERIODO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_PORCENTAJE_ACT_DEPTO_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_PORCENTAJE_ACT_DEPTO_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACTIVIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CANTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CATEGORIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MUNICIPIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACTIVIDAD {
            get {
                return this.ACTIVIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.ACTIVIDADField, value) != true)) {
                    this.ACTIVIDADField = value;
                    this.RaisePropertyChanged("ACTIVIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CANTIDAD {
            get {
                return this.CANTIDADField;
            }
            set {
                if ((this.CANTIDADField.Equals(value) != true)) {
                    this.CANTIDADField = value;
                    this.RaisePropertyChanged("CANTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CATEGORIA {
            get {
                return this.CATEGORIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CATEGORIAField, value) != true)) {
                    this.CATEGORIAField = value;
                    this.RaisePropertyChanged("CATEGORIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPARTAMENTO {
            get {
                return this.DEPARTAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPARTAMENTOField, value) != true)) {
                    this.DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MUNICIPIO {
            get {
                return this.MUNICIPIOField;
            }
            set {
                if ((object.ReferenceEquals(this.MUNICIPIOField, value) != true)) {
                    this.MUNICIPIOField = value;
                    this.RaisePropertyChanged("MUNICIPIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_OBTIENE_MATRIZ_PROYECTOS_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_OBTIENE_MATRIZ_PROYECTOS_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACTIVIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPTO_EMPRESAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPTO_PROYECTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIRECCION_COMERCIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMPRESAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROYECTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TELEFONOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACTIVIDAD {
            get {
                return this.ACTIVIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.ACTIVIDADField, value) != true)) {
                    this.ACTIVIDADField = value;
                    this.RaisePropertyChanged("ACTIVIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPTO_EMPRESA {
            get {
                return this.DEPTO_EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPTO_EMPRESAField, value) != true)) {
                    this.DEPTO_EMPRESAField = value;
                    this.RaisePropertyChanged("DEPTO_EMPRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPTO_PROYECTO {
            get {
                return this.DEPTO_PROYECTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPTO_PROYECTOField, value) != true)) {
                    this.DEPTO_PROYECTOField = value;
                    this.RaisePropertyChanged("DEPTO_PROYECTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCION_COMERCIAL {
            get {
                return this.DIRECCION_COMERCIALField;
            }
            set {
                if ((object.ReferenceEquals(this.DIRECCION_COMERCIALField, value) != true)) {
                    this.DIRECCION_COMERCIALField = value;
                    this.RaisePropertyChanged("DIRECCION_COMERCIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESAField, value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROYECTO {
            get {
                return this.PROYECTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PROYECTOField, value) != true)) {
                    this.PROYECTOField = value;
                    this.RaisePropertyChanged("PROYECTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TELEFONO {
            get {
                return this.TELEFONOField;
            }
            set {
                if ((this.TELEFONOField.Equals(value) != true)) {
                    this.TELEFONOField = value;
                    this.RaisePropertyChanged("TELEFONO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_OBTIENE_ACTIVIDAD_GIS_CTY", Namespace="http://schemas.datacontract.org/2004/07/DominioEntidades.Hydro")]
    [System.SerializableAttribute()]
    public partial class O_OBTIENE_ACTIVIDAD_GIS_CTY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACTIVIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ID_ACTIVIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACTIVIDAD {
            get {
                return this.ACTIVIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.ACTIVIDADField, value) != true)) {
                    this.ACTIVIDADField = value;
                    this.RaisePropertyChanged("ACTIVIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID_ACTIVIDAD {
            get {
                return this.ID_ACTIVIDADField;
            }
            set {
                if ((this.ID_ACTIVIDADField.Equals(value) != true)) {
                    this.ID_ACTIVIDADField = value;
                    this.RaisePropertyChanged("ID_ACTIVIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.anh.gob.bo:8443", ConfigurationName="ServicioConsultasHydro.IServicioHydroConsultas")]
    public interface IServicioHydroConsultas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerPersonaPorCI", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerPersonaPorCIRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_PERSONA_CTY> ObtenerPersonaPorCI(string credencial, string ci, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerEntidadPorDocumen" +
            "to", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerEntidadPorDocumen" +
            "toResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_ENTIDAD_CTY> ObtenerEntidadPorDocumento(string credencial, string cite, decimal idTipoDocumento, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/GenerarCorrelativo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/GenerarCorrelativoRespon" +
            "se")]
        AnhAgenteServicios.ServicioConsultasHydro.O_CORRELATIVO_CTY GenerarCorrelativo(decimal decIdSolicitante, decimal decIdTipoEnvio, decimal decIdTipoDocumento, string credencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/BuscarVehiculo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/BuscarVehiculoResponse")]
        AnhAgenteServicios.ServicioConsultasHydro.O_DETALLE_VEHICULO_CTY BuscarVehiculo(string credencial, decimal decIdTipoConsulta, string strDato, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/BuscarFuncionario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/BuscarFuncionarioRespons" +
            "e")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_PERSONA_CTY> BuscarFuncionario(string credencial, decimal decFiltro, string strDato, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ReporteVehiculo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ReporteVehiculoResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.E_VEHICULO_DATO_CTY> ReporteVehiculo(string strCredencial, string strDatoBuscar, decimal decTipoConsulta, decimal decTipoReporte, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerEntidadPorNombre", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerEntidadPorNombreR" +
            "esponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_ENTIDAD_CTY> ObtenerEntidadPorNombre(string credencial, string nombre, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerBusquedaPersona", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerBusquedaPersonaRe" +
            "sponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_PERSONA_BUSQUEDA_CTY> ObtenerBusquedaPersona(string strValorBusqueda, decimal decTipoConsulta, decimal decNroRegistrosMostrar, string strDominio, string strCredencial, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerFotoPersona", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerFotoPersonaRespon" +
            "se")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_FOTO_PERSONA_CTY> ObtenerFotoPersona(decimal decIdPersona, string strCredencialHydro, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerDatosUsuarioAnh", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerDatosUsuarioAnhRe" +
            "sponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_DATO_USUARIO_ANH_CTY> ObtenerDatosUsuarioAnh(decimal decIdUsuario, string strCredencialHydro, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtieneIdDocumentoEntida" +
            "d", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtieneIdDocumentoEntida" +
            "dResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_OBT_DOCUMENTO_CTY> ObtieneIdDocumentoEntidad(decimal decIdEntidad, string strCredencialHydro, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtieneUsuario", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtieneUsuarioResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_OBT_USUARIO_CTY> ObtieneUsuario(string strNombre, string strCredencialHydro, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ReporteActividad", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ReporteActividadResponse" +
            "")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_REPORTE_ACTIVIDAD_NAC_CTY> ReporteActividad(decimal decIdDepartamento, string strCredencialHydro, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerEntidadesActivida" +
            "d", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtenerEntidadesActivida" +
            "dResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_OBTIENE_ENTIDADES_ACT_CTY> ObtenerEntidadesActividad(string strCredencialHydro, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ReporteEmisionPeriodo", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ReporteEmisionPeriodoRes" +
            "ponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_EMISION_PERIODO_CERT_CTY> ReporteEmisionPeriodo(string strCredencialHydro, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ReportePorcentajeActDept" +
            "o", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ReportePorcentajeActDept" +
            "oResponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_PORCENTAJE_ACT_DEPTO_CTY> ReportePorcentajeActDepto(string strCredencialHydro, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ReporteMatrizProyectos", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ReporteMatrizProyectosRe" +
            "sponse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_OBTIENE_MATRIZ_PROYECTOS_CTY> ReporteMatrizProyectos(string strCredencialHydro, ref string mensajeError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtieneActividadGis", ReplyAction="http://servicios.anh.gob.bo:8443/IServicioHydroConsultas/ObtieneActividadGisRespo" +
            "nse")]
        System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_OBTIENE_ACTIVIDAD_GIS_CTY> ObtieneActividadGis(string strCredencialHydro, ref string mensajeError);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioHydroConsultasChannel : AnhAgenteServicios.ServicioConsultasHydro.IServicioHydroConsultas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioHydroConsultasClient : System.ServiceModel.ClientBase<AnhAgenteServicios.ServicioConsultasHydro.IServicioHydroConsultas>, AnhAgenteServicios.ServicioConsultasHydro.IServicioHydroConsultas {
        
        public ServicioHydroConsultasClient() {
        }
        
        public ServicioHydroConsultasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioHydroConsultasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioHydroConsultasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioHydroConsultasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_PERSONA_CTY> ObtenerPersonaPorCI(string credencial, string ci, ref string mensajeError) {
            return base.Channel.ObtenerPersonaPorCI(credencial, ci, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_ENTIDAD_CTY> ObtenerEntidadPorDocumento(string credencial, string cite, decimal idTipoDocumento, ref string mensajeError) {
            return base.Channel.ObtenerEntidadPorDocumento(credencial, cite, idTipoDocumento, ref mensajeError);
        }
        
        public AnhAgenteServicios.ServicioConsultasHydro.O_CORRELATIVO_CTY GenerarCorrelativo(decimal decIdSolicitante, decimal decIdTipoEnvio, decimal decIdTipoDocumento, string credencial, ref string mensajeError) {
            return base.Channel.GenerarCorrelativo(decIdSolicitante, decIdTipoEnvio, decIdTipoDocumento, credencial, ref mensajeError);
        }
        
        public AnhAgenteServicios.ServicioConsultasHydro.O_DETALLE_VEHICULO_CTY BuscarVehiculo(string credencial, decimal decIdTipoConsulta, string strDato, ref string mensajeError) {
            return base.Channel.BuscarVehiculo(credencial, decIdTipoConsulta, strDato, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_PERSONA_CTY> BuscarFuncionario(string credencial, decimal decFiltro, string strDato, ref string mensajeError) {
            return base.Channel.BuscarFuncionario(credencial, decFiltro, strDato, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.E_VEHICULO_DATO_CTY> ReporteVehiculo(string strCredencial, string strDatoBuscar, decimal decTipoConsulta, decimal decTipoReporte, ref string mensajeError) {
            return base.Channel.ReporteVehiculo(strCredencial, strDatoBuscar, decTipoConsulta, decTipoReporte, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_ENTIDAD_CTY> ObtenerEntidadPorNombre(string credencial, string nombre, ref string mensajeError) {
            return base.Channel.ObtenerEntidadPorNombre(credencial, nombre, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_PERSONA_BUSQUEDA_CTY> ObtenerBusquedaPersona(string strValorBusqueda, decimal decTipoConsulta, decimal decNroRegistrosMostrar, string strDominio, string strCredencial, ref string mensajeError) {
            return base.Channel.ObtenerBusquedaPersona(strValorBusqueda, decTipoConsulta, decNroRegistrosMostrar, strDominio, strCredencial, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_FOTO_PERSONA_CTY> ObtenerFotoPersona(decimal decIdPersona, string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ObtenerFotoPersona(decIdPersona, strCredencialHydro, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_DATO_USUARIO_ANH_CTY> ObtenerDatosUsuarioAnh(decimal decIdUsuario, string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ObtenerDatosUsuarioAnh(decIdUsuario, strCredencialHydro, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_OBT_DOCUMENTO_CTY> ObtieneIdDocumentoEntidad(decimal decIdEntidad, string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ObtieneIdDocumentoEntidad(decIdEntidad, strCredencialHydro, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_OBT_USUARIO_CTY> ObtieneUsuario(string strNombre, string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ObtieneUsuario(strNombre, strCredencialHydro, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_REPORTE_ACTIVIDAD_NAC_CTY> ReporteActividad(decimal decIdDepartamento, string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ReporteActividad(decIdDepartamento, strCredencialHydro, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_OBTIENE_ENTIDADES_ACT_CTY> ObtenerEntidadesActividad(string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ObtenerEntidadesActividad(strCredencialHydro, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_EMISION_PERIODO_CERT_CTY> ReporteEmisionPeriodo(string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ReporteEmisionPeriodo(strCredencialHydro, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_PORCENTAJE_ACT_DEPTO_CTY> ReportePorcentajeActDepto(string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ReportePorcentajeActDepto(strCredencialHydro, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_OBTIENE_MATRIZ_PROYECTOS_CTY> ReporteMatrizProyectos(string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ReporteMatrizProyectos(strCredencialHydro, ref mensajeError);
        }
        
        public System.Collections.Generic.List<AnhAgenteServicios.ServicioConsultasHydro.O_OBTIENE_ACTIVIDAD_GIS_CTY> ObtieneActividadGis(string strCredencialHydro, ref string mensajeError) {
            return base.Channel.ObtieneActividadGis(strCredencialHydro, ref mensajeError);
        }
    }
}
